import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const mockServices = [
  {
    slug: "3pl_central",
    name: "Extensiv (formerly 3PL Central)",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/367bbb1a-3d42-40ec-9ad9-f5a6eb43e480_tile_3pl_central.png",
    description: "Sync Extensiv Products, Inventory, Shipping Requests, Fulfillments, and Locations via Zimi.",
    documentation: "Extensiv (formerly 3PL Central) logistics connector. Supports Products, Inventory, Shipping Requests, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "3pl_ftp_v2",
    name: "FTP Fulfillment channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e4cd4611-6a50-4911-8705-a572b2680d22_tile_ftp.png",
    description: "FTP Fulfillment channel connector",
    documentation: "FTP Fulfillment channel logistics connector.",
    isActive: true,
  },
  {
    slug: "3plmock_v3",
    name: "Pipe17 Mock 3PL V3",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/38d83ce6-a1da-4b9b-a528-2f5f45b668b7_tile_pipe17.png",
    description: "This connector is used for testing 3pl operations",
    documentation: "Pipe17 Mock 3PL V3 connector used for testing 3PL operations.",
    isActive: true,
  },
  {
    slug: "acenda",
    name: "Acenda",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/316c7abd-ccbe-44fb-b742-e2cde2583fe9_tile_acenda.png",
    description: "Sync Orders, Fulfillments, Products, Inventory, and Locations via Zimi.",
    documentation: "Acenda ecommerce connector. Supports Orders, Fulfillments, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "acumatica",
    name: "Acumatica",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/87733609-d1d5-4b6f-ab06-09809460dc4b_tile_acumatica.png",
    description: "Sync Acumatica Orders, Inventory, Products, and Locations via Zimi.",
    documentation: "Acumatica finance connector. Supports Orders, Inventory, Products, and Locations.",
    isActive: true,
  },
  {
    slug: "aftership",
    name: "Aftership",
    logoUrl: "https://www.aftership.com/apple-touch-icon-1024x1024.png",
    description: "Process returns, manage exchanges, and sync customer refunds from your Aftership returns platform",
    documentation: "AfterShip RMA connector. Supports return processing, exchanges, and customer refunds.",
    isActive: true,
  },
  {
    slug: "agentmail",
    name: "Agentmail",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/agentmail_logo.png",
    description: "Receive and send emails using Agentmail",
    documentation: "Agentmail connector. Supports receiving and sending emails.",
    isActive: true,
  },
  {
    slug: "alom",
    name: "ALOM",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8d1e1bb5-148e-4b98-b990-31ecd8e5b49e_tile_alom.png",
    description: "Sync Alom Shipping Requests, Fulfillments, Inventory, and Locations via Zimi.",
    documentation: "ALOM logistics connector. Supports Shipping Requests, Fulfillments, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "amazon",
    name: "Amazon",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/amazon-logo.png",
    description: "Sync Orders, Returns, Products, Fulfillments, and Locations via Handled.",
    documentation: "Amazon Seller Central ecommerce connector. Supports Orders, Returns, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "amazon_awd",
    name: "Amazon Warehouse Distribution (AWD)",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/2a578e03-9f31-4260-b375-72f988140189_tile_amazon_mcf.png",
    description: "Sync Amazon AWD Inventory via Zimi.",
    documentation: "Amazon AWD logistics connector. Supports Inventory synchronization.",
    isActive: true,
  },
  {
    slug: "amazonia_edi",
    name: "Amazonia EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/938c1c9c-6d9f-4664-b340-f661d6bb58cb_tile_pipe17.png",
    description: "Sync Amazonia EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Amazonia EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "amazon_inbound",
    name: "Amazon FBA Inbound",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ab4ce9d0-cb19-4fa9-9a20-ae983d696e29_tile_amazon_mcf.png",
    description: "Sync Amazon Inbound Orders via Zimi.",
    documentation: "Amazon FBA Inbound logistics connector. Supports inbound order synchronization.",
    isActive: true,
  },
  {
    slug: "amazon_mcf",
    name: "Amazon MCF",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/0689a6f3-d64d-48c0-a92e-6553ce6918e8_tile_amazon_mcf.png",
    description: "Sync Shipping requests, Products, Inventory, Transfer Orders, and Locations via Zimi.",
    documentation: "Amazon MCF logistics connector. Supports Shipping Requests, Products, Inventory, Transfer Orders, and Locations.",
    isActive: true,
  },
  {
    slug: "amazon_mcf_sandbox",
    name: "MCF Sandbox - Pipe17 use only",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/fdc84053-cb38-4da3-baef-fc57f31c48ff_tile_pipe17.png",
    description: "Sync with Zimi",
    documentation: "Amazon MCF Sandbox logistics connector for Pipe17 internal use.",
    isActive: true,
  },
  {
    slug: "amazons3",
    name: "Amazon S3",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/00a81d78-a510-4994-a0f6-2649cb6bd9dc_tile_amazons3.png",
    description: "Amazon S3 connector",
    documentation: "Amazon S3 finance connector.",
    isActive: true,
  },
  {
    slug: "amazon_vc",
    name: "Amazon Vendor Central V3",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/dd8fd3f4-29fb-4e20-a260-32f317f86f7b_tile_amazon_vendor_central.png",
    description: "Pull orders and shipping labels, send back inventory and fulfillments",
    documentation: "Amazon Vendor Central V3 ecommerce connector. Supports orders, shipping labels, inventory, and fulfillments.",
    isActive: true,
  },
  {
    slug: "amazon_vendor_central",
    name: "Amazon Vendor Central",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/d2d3fa4a-6182-4ec9-b351-44bdc9f71acf_tile_amazon-vendor-central.png",
    description: "Manage Amazon Vendor Central orders in Zimi",
    documentation: "Amazon Vendor Central ecommerce connector.",
    isActive: true,
  },
  {
    slug: "anthropologie_edi",
    name: "Urban Outfitters EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ed8f31bb-f8ad-4cd5-ba13-6c1bcc412122_tile_pipe17.png",
    description: "Sync Urban Outfitters EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Urban Outfitters EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "apparelmagic",
    name: "ApparelMagic",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/41314f63-42a5-4d44-b60a-70eb4ff953e6_tile_apparelmagic.png",
    description: "ApparelMagic connector",
    documentation: "ApparelMagic ecommerce connector.",
    isActive: true,
  },
  {
    slug: "barrett",
    name: "Barrett",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/cbe72272-4024-43f7-9634-3c8c41d520f2_tile_barret.png",
    description: "Sync Barrett Shipping Requests, Inventory, Fulfillments, Arrivals, and Locations via Zimi.",
    documentation: "Barrett logistics connector. Supports Shipping Requests, Inventory, Fulfillments, Arrivals, and Locations.",
    isActive: true,
  },
  {
    slug: "bender",
    name: "Bender 3PL",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/00ea0daa-44dc-4831-8fd8-6c851d276943_tile_bender.png",
    description: "Bender 3PL connector",
    documentation: "Bender 3PL logistics connector.",
    isActive: true,
  },
  {
    slug: "bergen",
    name: "Bergen Logistics",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/82a126fe-2b2a-40d7-8e2b-a7d2cdb12732_tile_bergen.png",
    description: "Sync Bergen Logistics Shipping Requests, Fulfillments, Products, Inventory, Arrivals, Receipts, and Locations via Zimi.",
    documentation: "Bergen Logistics connector. Supports Shipping Requests, Fulfillments, Products, Inventory, Arrivals, Receipts, and Locations.",
    isActive: true,
  },
  {
    slug: "bestbuy_edi",
    name: "BestBuy EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/607bbfdd-7d2c-47c8-a872-82881d6c7ab2_tile_pipe17.png",
    description: "Sync BestBuy EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "BestBuy EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "bigcommerce_v3",
    name: "BigCommerce",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/31ca2403-5156-46f6-9e99-616173ed79c0_tile_bigcommerce.png",
    description: "Sync BigCommerce Orders, Inventory, Products, Fulfillments, and Locations via Zimi.",
    documentation: "BigCommerce ecommerce connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "boxc",
    name: "BoxC",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/de8d27d0-943d-4cc2-9885-9defe4852fd7_tile_boxc.png",
    description: "Sync BoxC Products, Inventory, Fulfillments, Shipping Requests, Arrivals, and Receipts via Zimi.",
    documentation: "BoxC logistics connector. Supports Products, Inventory, Fulfillments, Shipping Requests, Arrivals, and Receipts.",
    isActive: true,
  },
  {
    slug: "brandboom",
    name: "Brandboom",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4f2d472e-baaa-4b93-95d0-ff0937da2461_tile_brandboom.png",
    description: "Sync Brandboom Orders, Products, Inventory, and Locations via Zimi.",
    documentation: "Brandboom ecommerce connector. Supports Orders, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "brightpearl",
    name: "Brightpearl",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/0fb05ef6-bdef-4c22-94b7-0ed29856a150_tile_brightpearl.png",
    description: "Brightpearl connector",
    documentation: "Brightpearl ecommerce connector.",
    isActive: true,
  },
  {
    slug: "calibrate",
    name: "Calibrate 3PL",
    logoUrl: "https://merchant.withzimi.com/zimi_logos/Iso_2.png",
    description: "Calibrate 3PL connector",
    documentation: "Calibrate 3PL logistics connector.",
    isActive: true,
  },
  {
    slug: "capacityllc",
    name: "Capacity LLC 3PL",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/019e7a54-4c47-458f-8f68-a54e40862551_tile_capacityllc.png",
    description: "Capacity LLC 3PL connector",
    documentation: "Capacity LLC 3PL logistics connector.",
    isActive: true,
  },
  {
    slug: "carro_erp",
    name: "Carro Retail",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/cbe9fcae-ee22-443f-afc3-ae4568c83696_tile_carro.png",
    description: "Connector for Carro's Retailer Flow",
    documentation: "Carro Retail ecommerce connector.",
    isActive: true,
  },
  {
    slug: "carro_supplier",
    name: "Carro Supplier",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/cc9fbf46-6d57-4abd-861b-8ce31329356c_tile_carro.png",
    description: "Carro Supplier connector",
    documentation: "Carro Supplier ecommerce connector.",
    isActive: true,
  },
  {
    slug: "cart_com",
    name: "Cart.com",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/f72cfd06-fd25-466d-a23f-ce69a33ca9b3_tile_cart_com.png",
    description: "Sync Cart.com Orders, Fulfillments, Products, Inventory, and Locations via Zimi.",
    documentation: "Cart.com ecommerce connector. Supports Orders, Fulfillments, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "cbip",
    name: "CBIP Logistics",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/73ad2f06-799b-4973-ab05-d37dffee2af5_tile_cbip.png",
    description: "Sync CBIP Shipments, Fulfillments, and Locations via Zimi.",
    documentation: "CBIP Logistics connector. Supports Shipments, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "cbp",
    name: "CBP Trade",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Seal_of_U.S._Customs_and_Border_Protection.png",
    description: "Auto file customs documents with the CBP using Handled",
    documentation: "CBP Trade logistics connector. Supports automated customs document filing.",
    isActive: true,
  },
  {
    slug: "channeladvisor",
    name: "Rithum - ChannelAdvisor",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/f7044003-86a8-4a44-9341-b2e7868fb462_tile_channeladvisor.png",
    description: "Sync Rithum - ChannelAdvisor - Products, Shipping Requests, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "Rithum (ChannelAdvisor) ecommerce connector. Supports Products, Shipping Requests, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "channelape",
    name: "ChannelApe",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8bee59a0-4bd2-4651-b351-ba835fdb544e_tile_channelape.png",
    description: "Sync ChannelApe Shipping Requests, Fulfillments, and Locations via Zimi.",
    documentation: "ChannelApe logistics connector. Supports Shipping Requests, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "chord",
    name: "Chord",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/fb48a7d6-7e89-4b10-a3aa-e561c07e044e_tile_chord.png",
    description: "Easily connect Chord's headless commerce platform to ERPs and Fulfillment, with rich Order and Inventory Management capabilities.",
    documentation: "Chord ecommerce connector. Supports Order and Inventory Management.",
    isActive: true,
  },
  {
    slug: "cin7",
    name: "Cin7 Omni",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/40862956-4382-41ee-97a4-ff3919c9f573_tile_cin7.png",
    description: "Cin7 connector",
    documentation: "Cin7 Omni finance connector.",
    isActive: true,
  },
  {
    slug: "circlify",
    name: "Full Circle (Circlify)",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/77ac69fe-c209-4ef5-961e-452f6a719022_tile_fullcircle.png",
    description: "Sync with Zimi",
    documentation: "Full Circle (Circlify) finance connector.",
    isActive: true,
  },
  {
    slug: "commercehub",
    name: "CommerceHub DSCO",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/116e7c8e-bfce-4aa1-8d88-aa0e671b755b_tile_commercehub.png",
    description: "CommerceHub (DSCO) connector",
    documentation: "CommerceHub DSCO ecommerce connector.",
    isActive: true,
  },
  {
    slug: "commercetools",
    name: "CommerceTools",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/1061bdc0-7b34-4161-b31f-5d796539fb6b_tile_commercetools.png",
    description: "Sync Orders, Products, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "CommerceTools ecommerce connector. Supports Orders, Products, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "costco_edi",
    name: "Costco EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/d7fd4740-bda5-4151-b62e-e64f347a9835_tile_pipe17.png",
    description: "Sync Costco EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Costco EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "davinci_v3",
    name: "Davinci",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/5f1c69cc-53af-4f13-b501-0b3a30dd4456_tile_davinci.png",
    description: "Sync DaVinci Products, Shipping Requests, Inventory, Arrivals, and Locations via Zimi.",
    documentation: "DaVinci logistics connector. Supports Products, Shipping Requests, Inventory, Arrivals, and Locations.",
    isActive: true,
  },
  {
    slug: "dear",
    name: "Cin7 Core",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/6587ebc8-8224-409f-a516-d6c66ccc50de_tile_dear.png",
    description: "DEAR connector",
    documentation: "Cin7 Core (formerly DEAR) finance connector.",
    isActive: true,
  },
  {
    slug: "deliverr_v3",
    name: "Flexport (was Deliverr)",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/fee32ca4-2623-43c9-baba-e77a61ea4430_tile_deliverr.png",
    description: "Sync Deliverr V3 Products, Shipping Requests, Fulfillments, Inventory, Receipts, Arrivals, and Locations via Zimi.",
    documentation: "Flexport (formerly Deliverr) logistics connector. Supports Products, Shipping Requests, Fulfillments, Inventory, Receipts, Arrivals, and Locations.",
    isActive: true,
  },
  {
    slug: "deposco",
    name: "Deposco",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/depsoco_logo.webp",
    description: "Manage inventory, process orders, and sync warehouse data from your Deposco fulfillment platform",
    documentation: "Deposco WMS connector. Supports inventory management, order processing, and warehouse data sync.",
    isActive: true,
  },
  {
    slug: "deposco_v2",
    name: "Deposco V2",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/depsoco_logo.webp",
    description: "Manage inventory, process orders, and sync warehouse data from your Deposco fulfillment platform",
    documentation: "Deposco V2 WMS connector. Supports inventory management, order processing, and warehouse data sync.",
    isActive: true,
  },
  {
    slug: "easypost",
    name: "Easypost",
    logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQK_4uI2SmM0mlLwj1c9UctgT5aVP6Rk2mjzg&s",
    description: "Connect Carrier Accounts, Buy Shipping Labels",
    documentation: "EasyPost carrier connector. Supports carrier account management and shipping label purchases.",
    isActive: true,
  },
  {
    slug: "ebay",
    name: "eBay",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/426e432c-bef2-4d3d-ad1a-4588a457eefe_tile_ebay.png",
    description: "Sync eBay Orders, Products, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "eBay ecommerce connector. Supports Orders, Products, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "ecommmock_v3",
    name: "Pipe17 Mock Ecommerce",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/84852c42-7fb3-4702-a312-157855ccffcc_tile_pipe17.png",
    description: "This connector is used for testing e-commerce operations",
    documentation: "Pipe17 Mock Ecommerce connector used for testing e-commerce operations.",
    isActive: true,
  },
  {
    slug: "ecwid",
    name: "Ecwid",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e1f5aa63-f3f7-4ac9-9ba5-982da67346f0_tile_ecwid.png",
    description: "Sync Ecwid Orders, Fulfillments, Products, Inventory, and Locations via Zimi.",
    documentation: "Ecwid ecommerce connector. Supports Orders, Fulfillments, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "email",
    name: "Email",
    logoUrl: "https://automation-specialist.itshandled.ai/zimi_logos/Iso_1.png",
    description: "Send emails with Handled",
    documentation: "Email logistics connector. Supports sending emails.",
    isActive: true,
  },
  {
    slug: "email_3pl",
    name: "Email Fulfillment",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/c1b80a32-e80c-428d-80cb-55abe2ce6100_tile_pipe17.png",
    description: "Send fulfillment orders via email.",
    documentation: "Email Fulfillment logistics connector. Supports sending fulfillment orders via email.",
    isActive: true,
  },
  {
    slug: "emobot_brain",
    name: "Emobot Brain",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/deposco_logo.png",
    description: "Sync Emobot knowledges",
    documentation: "Emobot Brain ecommerce connector.",
    isActive: true,
  },
  {
    slug: "etsy",
    name: "Etsy",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7d1abeae-a4f3-44a4-ad26-cbe8043bfeb8_tile_etsy.png",
    description: "Sync Etsy Orders, Products, Inventory, and Fulfillments via Zimi.",
    documentation: "Etsy ecommerce connector. Supports Orders, Products, Inventory, and Fulfillments.",
    isActive: true,
  },
  {
    slug: "excelsior_v3",
    name: "Excelsior",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/de146735-08bf-461b-a98c-62c872bc0a7e_tile_excelsior.png",
    description: "Sync Excelsior Shipping Requests, Fulfillments, Inventory, and Locations via Zimi.",
    documentation: "Excelsior logistics connector. Supports Shipping Requests, Fulfillments, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "extensiv",
    name: "Extensiv",
    logoUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcrCaUzfBJzxvxk2a4CARQHmoO3Jop_eVtHg&s",
    description: "Sync Orders, Inventory, Products, Fulfillments, and Locations via Handled.",
    documentation: "Extensiv ecommerce connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "extron",
    name: "extron",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/119b4332-ba53-4af8-9f90-d26c615722c3_tile_extron.png",
    description: "Sync with Zimi",
    documentation: "Extron logistics connector.",
    isActive: true,
  },
  {
    slug: "fabric",
    name: "Fabric",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/9f800ca4-4974-4ba1-aaca-e2b71d917bc2_tile_fabric_io.png",
    description: "Sync Fabric Orders, Inventory, and Fulfillments via Zimi.",
    documentation: "Fabric ecommerce connector. Supports Orders, Inventory, and Fulfillments.",
    isActive: true,
  },
  {
    slug: "faire",
    name: "Faire",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4c27ddc8-2586-4841-bb67-f401bc3c963c_tile_faire.png",
    description: "Sync Faire Orders, Products, Inventory, and Locations via Zimi.",
    documentation: "Faire ecommerce connector. Supports Orders, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "fedex",
    name: "Fedex",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4aaa4fcc-7245-430b-85e0-99d1368710dc_fedex.png",
    description: "Get Shipping rates, Shipping labels from your Fedex Account",
    documentation: "FedEx carrier connector. Supports shipping rates, labels, and carrier account management.",
    isActive: true,
  },
  {
    slug: "fedex_supply_chain",
    name: "FedEx Supply Chain",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/a0451b99-d311-4438-b6cc-e95f27fadcb7_tile_fedex.png",
    description: "Sync with Zimi",
    documentation: "FedEx Supply Chain logistics connector.",
    isActive: true,
  },
  {
    slug: "feedonomics",
    name: "Feedonomics",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/f89c2330-7481-4b06-be1d-2615c010e3da_tile_feedonomics.png",
    description: "Sync Feedonomics Orders, and Fulfillments via Zimi.",
    documentation: "Feedonomics ecommerce connector. Supports Orders and Fulfillments.",
    isActive: true,
  },
  {
    slug: "finale_inventory",
    name: "Finale Inventory",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/bc4410f2-7199-4a06-b748-657311dc7e53_tile_finale_inventory.png",
    description: "Sync with Zimi",
    documentation: "Finale Inventory finance connector.",
    isActive: true,
  },
  {
    slug: "ftp_ecomm",
    name: "FTP Seller channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/b49e1af1-bc5e-4f92-907e-25ba626fcd99_tile_ftp-ecomm.png",
    description: "FTP Seller channel connector",
    documentation: "FTP Seller channel ecommerce connector.",
    isActive: true,
  },
  {
    slug: "fulfil_io",
    name: "Fulfil.io Sales",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/2d3185d3-1a52-4dc1-bd0a-19eaaed9da2d_tile_fulfil_io.png",
    description: "Fulfil.io Sales connector",
    documentation: "Fulfil.io Sales ecommerce connector.",
    isActive: true,
  },
  {
    slug: "fullcircle",
    name: "FullCircle",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/b5696f7b-f4b7-407c-b81b-6bea6fd1dd3c_tile_fullcircle.png",
    description: "Sync with Zimi",
    documentation: "FullCircle finance connector.",
    isActive: true,
  },
  {
    slug: "gmail",
    name: "Gmail",
    logoUrl: "https://static.vecteezy.com/system/resources/thumbnails/020/964/377/small_2x/gmail-mail-icon-for-web-design-free-png.png",
    description: "Sync emails from Gmail",
    documentation: "Gmail connector. Supports reading, sending, and managing emails.",
    isActive: true,
  },
  {
    slug: "googlesheet",
    name: "Google Sheet",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Google_Sheets_2020_Logo.svg/1200px-Google_Sheets_2020_Logo.svg.png",
    description: "Create and collaborate on tables",
    documentation: "Google Sheets connector. Supports reading and writing spreadsheet data.",
    isActive: true,
  },
  {
    slug: "greenspoon",
    name: "GreenSpoon",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7af6fb30-5d1f-4bdc-994b-49671c76affd_tile_greenspoon.png",
    description: "Sync GreenSpoon Orders, Products, Fulfillments, Inventory, and Locations via Zimi.",
    documentation: "GreenSpoon finance connector. Supports Orders, Products, Fulfillments, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "happy_returns",
    name: "Happy Returns",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Happy_Returns_Icon.svg",
    description: "Manage RMA's, return packages from Happy Returns",
    documentation: "Happy Returns RMA connector. Supports RMA management and return package processing.",
    isActive: true,
  },
  {
    slug: "houzz",
    name: "Houzz",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/01e1934c-7803-4804-b8ca-ce3363258a7e_tile_houzz.png",
    description: "Manage your Houzz orders, fulfillments, products and inventory via Zimi.",
    documentation: "Houzz ecommerce connector. Supports orders, fulfillments, products, and inventory.",
    isActive: true,
  },
  {
    slug: "hubspot",
    name: "Hubspot",
    logoUrl: "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/168_Hubspot_logo_logos-512.png",
    description: "Track deals with Hubspot",
    documentation: "HubSpot CRM connector. Supports deals, contacts, companies, and order tracking.",
    isActive: true,
  },
  {
    slug: "infoplus",
    name: "Infoplus",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8ae2418b-d80d-4f81-8251-5d365aa1fbd3_tile_infoplus.png",
    description: "Sync Infoplus Shipping Requests, Products, Inventory, and Locations via Zimi.",
    documentation: "Infoplus logistics connector. Supports Shipping Requests, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "inventoryplanner_com",
    name: "InventoryPlanner",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/650b1047-d09e-40ea-acd8-2d3699e512ea_tile_inventory-planner.png",
    description: "InventoryPlanner.com connector",
    documentation: "InventoryPlanner ecommerce connector.",
    isActive: true,
  },
  {
    slug: "its",
    name: "ITS Logistics",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e2dea62a-a9e2-4692-9a5b-a70a8c98613c_tile_its.png",
    description: "ITS connector",
    documentation: "ITS Logistics connector.",
    isActive: true,
  },
  {
    slug: "jazz_central",
    name: "Jazz Central",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/52b8c34e-1dd2-4da6-b149-5c1d62749b4d_tile_jazz-central.png",
    description: "Jazz Central connector",
    documentation: "Jazz Central logistics connector.",
    isActive: true,
  },
  {
    slug: "katana",
    name: "Katana",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ff63aeb9-2ca6-4283-90b4-024148ca957c_tile_katana.png",
    description: "Sync Katana Orders, Products, and Inventory via Zimi.",
    documentation: "Katana finance connector. Supports Orders, Products, and Inventory.",
    isActive: true,
  },
  {
    slug: "lightspeed",
    name: "Lightspeed",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/a581a042-d599-4bf4-8202-1efa86426927_tile_lightspeed.png",
    description: "Lightspeed connector",
    documentation: "Lightspeed ecommerce connector.",
    isActive: true,
  },
  {
    slug: "logiwa",
    name: "Logiwa WMS",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/6d38bcd9-5569-4a99-a529-9076d8e3e74c_tile_logiwa.png",
    description: "Logiwa connector",
    documentation: "Logiwa WMS logistics connector. Supports warehouse management, shipping requests, and inventory.",
    isActive: true,
  },
  {
    slug: "logiwa_io",
    name: "Logiwa.io",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/dccc766f-fe98-4af0-ba0e-e635882de915_tile_logiwa.png",
    description: "Logiwa connector",
    documentation: "Logiwa.io logistics connector.",
    isActive: true,
  },
  {
    slug: "loop",
    name: "Loop",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/0127f3c7-22a6-4f1d-a42e-15fe37ce5dfd_tile_loop.png",
    description: "Process returns, manage exchanges, and sync customer refunds from your Loop returns platform",
    documentation: "Loop Returns RMA connector. Supports return processing, exchanges, and customer refunds.",
    isActive: true,
  },
  {
    slug: "mabang",
    name: "Mabang",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4ec294e0-edec-4661-8663-24fb5a0bb46c_tile_mabang.png",
    description: "The Mabang connector is primarily used to send orders to Mabang from Zimi.",
    documentation: "Mabang logistics connector. Primarily used to send orders to Mabang.",
    isActive: true,
  },
  {
    slug: "magento_v3",
    name: "Magento",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/04816dec-f293-4a56-b2db-1bc93595162a_tile_magento.png",
    description: "Sync Magento Orders, Products, Inventory, and Locations via Zimi.",
    documentation: "Magento ecommerce connector. Supports Orders, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "masonhub",
    name: "MasonHub",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/2c3980a8-96a5-4ffd-9b8c-08716c226d78_tile_masonhub.png",
    description: "Sync MasonHub Products, Shipping Requests, Fulfillments, Inventory, Arrivals, Returns, and Locations via Zimi.",
    documentation: "MasonHub logistics connector. Supports Products, Shipping Requests, Fulfillments, Inventory, Arrivals, Returns, and Locations.",
    isActive: true,
  },
  {
    slug: "mintsoft",
    name: "Mintsoft",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8526cf22-3080-4366-b99a-1985b7481038_tile_mintsoft.png",
    description: "Sync Mintsoft Shipping Requests, Products, Inventory, Arrivals, Receipts, and Locations via Zimi.",
    documentation: "Mintsoft logistics connector. Supports Shipping Requests, Products, Inventory, Arrivals, Receipts, and Locations.",
    isActive: true,
  },
  {
    slug: "mirakl",
    name: "Mirakl",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4814866c-b87a-4ec4-bcfc-e7645746bf55_tile_mirakl.png",
    description: "Manage marketplace sellers, process orders, and sync product catalogs from your Mirakl marketplace platform",
    documentation: "Mirakl marketplace connector. Supports seller management, order processing, and product catalog sync.",
    isActive: true,
  },
  {
    slug: "mirakl_connect",
    name: "MIRAKL Connect",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/6ba81483-631e-405e-8b17-05522f7cf151_tile_mirakl.png",
    description: "MIRAKL Connect connector",
    documentation: "MIRAKL Connect ecommerce connector.",
    isActive: true,
  },
  {
    slug: "mirakl_mp",
    name: "MIRAKL MP",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/598f091e-bbb9-4752-afc0-4bb30c4c83aa_tile_mirakl.png",
    description: "MIRAKL MP connector",
    documentation: "MIRAKL MP ecommerce connector.",
    isActive: true,
  },
  {
    slug: "mochila_3pl",
    name: "Mochila 3PL",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/3495a935-bd56-48cd-b293-79a5ffce470e_tile_mochila.png",
    description: "Sync Mochila Products, Shipping Requests, Inventory, Returns, and Locations via Zimi.",
    documentation: "Mochila 3PL logistics connector. Supports Products, Shipping Requests, Inventory, Returns, and Locations.",
    isActive: true,
  },
  {
    slug: "netsuite_b2b",
    name: "NetSuite B2B",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ce5b9ca6-1f8d-4337-922c-79a2a8f9df76_tile_netsuite.png",
    description: "The NetSuite B2B connector is primarily used to send orders to NetSuite B2B from Zimi.",
    documentation: "NetSuite B2B finance connector. Primarily used to send orders to NetSuite B2B.",
    isActive: true,
  },
  {
    slug: "netsuite_ecomm",
    name: "NetSuite E-commerce V3",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/0c7ef75a-3f53-43a2-b007-c9c5eb5772b6_tile_netsuite.png",
    description: "The NetSuite e-commerce connector is primarily used when you are pulling orders from NetSuite to be sent out to fulfillment channels",
    documentation: "NetSuite E-commerce V3 connector. Pulls orders from NetSuite to fulfillment channels.",
    isActive: true,
  },
  {
    slug: "netsuite_e_commerce",
    name: "NetSuite E-commerce 1.0",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e7cec3b3-5bed-4238-b981-ac09013ca4ab_tile_netsuite.png",
    description: "The NetSuite e-commerce connector is primarily used when you are pulling orders from NetSuite to be sent out to fulfillment channels",
    documentation: "NetSuite E-commerce 1.0 connector. Pulls orders from NetSuite to fulfillment channels.",
    isActive: true,
  },
  {
    slug: "netsuite_erp",
    name: "NetSuite ERP",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/5e8f5ae0-017e-4dfc-ae2f-80a6f99d0721_tile_netsuite.png",
    description: "The NetSuite ERP connector is primarily used to send orders to NetSuite from Zimi.",
    documentation: "NetSuite ERP finance connector. Syncs marketplace/selling channel orders into NetSuite.",
    isActive: true,
  },
  {
    slug: "netsuite_erp_v2",
    name: "NetSuite ERP V2",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/08c40e28-3b8b-49de-9a35-2fcc6191203d_tile_netsuite.png",
    description: "The NetSuite ERP connector is primarily used to send orders to NetSuite from Zimi.",
    documentation: "NetSuite ERP V2 finance connector. Syncs marketplace/selling channel orders into NetSuite.",
    isActive: true,
  },
  {
    slug: "nordstrom_edi",
    name: "Nordstrom EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/70a95fc4-5d4b-4d3a-8444-d5dd05c9898e_tile_pipe17.png",
    description: "Sync Nordstrom EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Nordstrom EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "northstar",
    name: "NorthStar",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/5475f6b9-fcd6-4a5d-95a0-2f6d70d8e776_tile_northstar.png",
    description: "Sync NorthStar Shipping Requests, Fulfillments, Inventory, and Locations via Zimi.",
    documentation: "NorthStar logistics connector. Supports Shipping Requests, Fulfillments, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "nri",
    name: "NRI",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/b03a8942-d234-4a17-bcaf-f273d903c9c4_tile_nri.png",
    description: "NRI connector",
    documentation: "NRI logistics connector.",
    isActive: true,
  },
  {
    slug: "nuorder",
    name: "NuORDER",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/50f19266-1ee5-41d0-ac14-973c9169567d_tile_nuorder.png",
    description: "NuORDER connector",
    documentation: "NuORDER ecommerce connector.",
    isActive: true,
  },
  {
    slug: "odoo",
    name: "Odoo",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/9b84c009-5ef8-4422-8574-915ae726ce13_tile_odoo.png",
    description: "Sync Odoo Orders, Products, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "Odoo finance connector. Supports Orders, Products, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "orderdesk",
    name: "OrderDesk",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7b09c321-cdb7-4715-8ee2-be2136c089ab_tile_order_desk.png",
    description: "Sync OrderDesk Products, Shipping Requests, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "OrderDesk logistics connector. Supports Products, Shipping Requests, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "order_desk",
    name: "Order Desk",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ba4eef5c-314d-4c17-91ab-b50a056bdb4a_tile_order_desk.png",
    description: "OrderDesk connector",
    documentation: "Order Desk ecommerce connector.",
    isActive: true,
  },
  {
    slug: "orderdesk_3pl",
    name: "Orderdesk",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/orderdesk_logo.png",
    description: "Sync Orders, Inventory, Products, Fulfillments, and Locations via Zimi.",
    documentation: "Orderdesk ecommerce connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "orderful_edi",
    name: "Orderful EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/38450243-60e0-426d-852e-f15a830dc674_tile_orderful-edi.png",
    description: "Sync Orderful EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Orderful EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "orderful_labels",
    name: "UCC Labels Generator",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7a181747-3676-4506-8c33-d4c9c99d071e_tile_orderful-labels.png",
    description: "UCC Labels Generator",
    documentation: "UCC Labels Generator ecommerce connector.",
    isActive: true,
  },
  {
    slug: "orderhive",
    name: "Cin7 Orderhive",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/a7d85d21-5ea8-4a5f-a84e-a23b77d435e1_tile_orderhive.png",
    description: "Sync Cin7 Orderhive Orders, Products, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "Cin7 Orderhive ecommerce connector. Supports Orders, Products, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "osa_3pl",
    name: "OSA WMS",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/c4113d32-4218-490d-8e65-2aafd4866399_tile_osa-3pl.png",
    description: "OSA 3PL connector",
    documentation: "OSA WMS logistics connector.",
    isActive: true,
  },
  {
    slug: "osauc3",
    name: "OSA UC3",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e5966595-8f76-483c-8bbf-e779f24d492e_tile_osauc3.png",
    description: "OSA UC3 3PL connector",
    documentation: "OSA UC3 logistics connector.",
    isActive: true,
  },
  {
    slug: "packiyo",
    name: "Packiyo",
    logoUrl: "https://media.licdn.com/dms/image/v2/C560BAQG052nuP7_Oqw/company-logo_200_200/company-logo_200_200/0/1679614846684/packiyo_logo",
    description: "Manage inventory, process orders, and sync warehouse data from your Packiyo fulfillment platform",
    documentation: "Packiyo ecommerce connector. Supports inventory management, order processing, and warehouse data sync.",
    isActive: true,
  },
  {
    slug: "peoplevox",
    name: "PeopleVox",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/c26fd357-62a3-4446-9908-c0bcc4c72af6_tile_peoplevox.png",
    description: "Sync Products, Shipping Requests, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "PeopleVox logistics connector. Supports Products, Shipping Requests, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "petspiration_edi",
    name: "Petspiration EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/d5eb6b92-e092-4616-a5e3-092a6dbbeceb_tile_pipe17.png",
    description: "Sync Petspiration EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Petspiration EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "pfsweb",
    name: "PFS Web",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/a7e48db3-138b-4efb-989b-3bd7fd3f9f29_tile_pfsweb.png",
    description: "Sync PFS Web Shipping Requests, Fulfillments, Products, Inventory, Arrivals, Receipts, Returns, and Locations via Zimi.",
    documentation: "PFS Web logistics connector. Supports Shipping Requests, Fulfillments, Products, Inventory, Arrivals, Receipts, Returns, and Locations.",
    isActive: true,
  },
  {
    slug: "pipe17",
    name: "Pipe 17",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/pipe_17_logo.png",
    description: "Sync Orders, Inventory, Products, Fulfillments, and Locations via Zimi.",
    documentation: "Pipe17 logistics connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "pipe17_mock_3pl",
    name: "Pipe17 Mock 3PL (Legacy)",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e0c35475-06b0-49b8-8c85-1d8d44699ff4_tile_pipe17.png",
    description: "This connector is used for testing 3PL fulfillments",
    documentation: "Pipe17 Mock 3PL (Legacy) logistics connector for testing 3PL fulfillments.",
    isActive: true,
  },
  {
    slug: "pitneybowes",
    name: "PitneyBowes",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/d49ebf35-46ff-433b-872b-ef198d91ef97_tile_pitneybowes.png",
    description: "Sync PitneyBowes Products, Shipping Requests, Inventory, Fulfillments, Arrivals, Receipts and Locations via Zimi.",
    documentation: "PitneyBowes logistics connector. Supports Products, Shipping Requests, Inventory, Fulfillments, Arrivals, Receipts, and Locations.",
    isActive: true,
  },
  {
    slug: "portless",
    name: "Portless",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/732e58ed-68c7-40cf-8569-f75affa00094_portless.png",
    description: "Portless",
    documentation: "Portless logistics connector.",
    isActive: true,
  },
  {
    slug: "prestashop",
    name: "PrestaShop",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8612d7e1-40a0-4873-871e-58c0300e3a28_tile_prestashop.png",
    description: "Sync PrestaShop Orders, Products, Fulfillments, and Inventory via Zimi.",
    documentation: "PrestaShop ecommerce connector. Supports Orders, Products, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "printnode",
    name: "Print Node",
    logoUrl: "https://www.printnode.com/ui/images/branding/artwork/welcome-logo.png",
    description: "Send print jobs to any printer, anywhere in the world through a simple API",
    documentation: "PrintNode connector. Supports sending print jobs to any printer via API.",
    isActive: true,
  },
  {
    slug: "priority",
    name: "Priority",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/9c356989-0bcb-4c68-b5de-3feac7413344_tile_priority.png",
    description: "Priority connector",
    documentation: "Priority finance connector.",
    isActive: true,
  },
  {
    slug: "quickbooks",
    name: "QuickBooks",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/651e55ac-2d55-4ed7-957b-cb9f7f3038df_tile_quickbooks_online.png",
    description: "Quickbooks connector",
    documentation: "QuickBooks finance connector. Supports order and financial data synchronization.",
    isActive: true,
  },
  {
    slug: "redo",
    name: "Redo",
    logoUrl: "https://cdn.shopify.com/app-store/listing_images/0b8778a11e8f31ccf0ccc703a398f917/icon/COe7uufqgogDEAE=.png",
    description: "Process returns, manage exchanges, and sync customer refunds from your Redo returns platform",
    documentation: "Redo RMA connector. Supports return processing, exchanges, and customer refunds.",
    isActive: true,
  },
  {
    slug: "returnlogic",
    name: "Return Logic",
    logoUrl: "https://media.licdn.com/dms/image/v2/C560BAQHrOgN85Px58g/company-logo_200_200/company-logo_200_200/0/1668089623248/returnlogic_logo",
    description: "Sync Return Logic Returns, and Refunds via Zimi.",
    documentation: "Return Logic RMA connector. Supports return and refund synchronization.",
    isActive: true,
  },
  {
    slug: "returnly",
    name: "Returnly",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8c290215-e247-4f29-8ffe-8d1aeb71cacc_tile_returnly.png",
    description: "Sync Returnly Returns, and Refunds via Zimi.",
    documentation: "Returnly RMA connector. Supports return and refund synchronization.",
    isActive: true,
  },
  {
    slug: "returnzap",
    name: "ReturnZap",
    logoUrl: "https://cdn.shopify.com/app-store/listing_images/d565e8b71f68a19d6fe9df8f24ed60f5/icon/CN6fpLbYi_0CEAE=.png",
    description: "Process returns, manage exchanges, and sync customer refunds from your ReturnZap returns platform",
    documentation: "ReturnZap RMA connector. Supports return processing, exchanges, and customer refunds.",
    isActive: true,
  },
  {
    slug: "salesforce",
    name: "Salesforce B2C Commerce",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/af16a9fa-a566-4524-9e7e-daa47695a745_tile_salesforce.png",
    description: "Salesforce Commerce Cloud connector",
    documentation: "Salesforce B2C Commerce ecommerce connector.",
    isActive: true,
  },
  {
    slug: "selleractive",
    name: "SellerActive",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/a6717ed2-bdec-47e7-ad7e-7900912ebba8_tile_selleractive.png",
    description: "Sync Orders, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "SellerActive ecommerce connector. Supports Orders, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "sfsc",
    name: "Salesforce Service Cloud",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/64346706-81a3-4cfc-9707-874a70917cf8_tile_salesforce.png",
    description: "Salesforce Service Cloud connector",
    documentation: "Salesforce Service Cloud ecommerce connector.",
    isActive: true,
  },
  {
    slug: "shein",
    name: "SHEIN",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8a37fa8c-efa8-41db-a014-7691901e984e_tile_shein.png",
    description: "Sync Orders, Fulfillments, Products, Inventory and Locations via Zimi.",
    documentation: "SHEIN ecommerce connector. Supports Orders, Fulfillments, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "shipbob",
    name: "ShipBob",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/76b65e04-6719-4f6d-a7bb-acd0e5e16911_tile_shipbob.png",
    description: "Sync ShipBob Products, Shipping Requests, Inventory, Arrivals, and Locations via Zimi.",
    documentation: "ShipBob logistics connector. Supports Products, Shipping Requests, Inventory, Arrivals, and Locations.",
    isActive: true,
  },
  {
    slug: "shiphero",
    name: "Shiphero",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/c494bac6-c09e-472b-9dd4-e8bc7fc75b67_tile_shiphero.png",
    description: "Sync Shiphero Products, Shipping Requests, Inventory, Fulfillments, Arrivals, Receipts, and Locations via Handled.",
    documentation: "ShipHero WMS connector. Supports Products, Shipping Requests, Inventory, Fulfillments, Arrivals, Receipts, and Locations.",
    isActive: true,
  },
  {
    slug: "shipmonk",
    name: "Shipmonk",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7f952259-31cd-4083-a3da-f6574b2c8212_tile_shipmonk.png",
    description: "Shipmonk connector",
    documentation: "Shipmonk logistics connector.",
    isActive: true,
  },
  {
    slug: "shipsidekick",
    name: "Shipsidekick",
    logoUrl: "https://www.shipsidekick.com/favicon/favicon.svg",
    description: "Sync Orders, Inventory, Products, Fulfillments, and Locations via Handled.",
    documentation: "Shipsidekick ecommerce connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "shipstation_3pl",
    name: "ShipStation Fulfillment",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/3a52bd1c-e2bd-407c-be18-1473c9cc4d84_tile_shipstation.png",
    description: "Sync ShipStation Fulfillment Products, Shipping Requests, Fulfillments, and Locations via Zimi.",
    documentation: "ShipStation Fulfillment logistics connector. Supports Products, Shipping Requests, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "shipstation_sales_v3",
    name: "ShipStation Sales",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/2b1a4289-c7b1-4e9b-b3a6-cf8d0dfaa025_tile_shipstation.png",
    description: "Sync ShipStation Sales Orders, Products, Fulfillments, and Locations via Zimi.",
    documentation: "ShipStation Sales ecommerce connector. Supports Orders, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "shipwire",
    name: "Shipwire",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/5e90eba3-65d6-4d43-b526-76fb6c511198_tile_shipwire.png",
    description: "Shipwire connector",
    documentation: "Shipwire logistics connector.",
    isActive: true,
  },
  {
    slug: "shopbop_edi",
    name: "Shopbop EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/db8a495d-dca1-484a-a2b6-b6f8c00ab285_tile_pipe17.png",
    description: "Sync Shopbop EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Shopbop EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "shopify",
    name: "Shopify",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/shopify-logo-png-transparent.png",
    description: "Manage products, process orders, and sync customer data from your Shopify store",
    documentation: "Shopify ecommerce connector. Supports Orders, Products, Fulfillments, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "shopify_b2b",
    name: "Shopify B2B (beta)",
    logoUrl: "https://merchant.withzimi.com/zimi_logos/Iso_2.png",
    description: "Manage your Shopify B2B orders, fulfillments, products and inventory via Zimi.",
    documentation: "Shopify B2B ecommerce connector (beta). Supports orders, fulfillments, products, and inventory.",
    isActive: true,
  },
  {
    slug: "shopify_fs",
    name: "Shopify Fulfillment Service",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/b005dc8b-2e01-458d-9867-5e3b5ea9eeca_tile_shopify.png",
    description: "Manage your Shopify orders, fulfillments and inventory via Zimi.",
    documentation: "Shopify Fulfillment Service ecommerce connector. Supports orders, fulfillments, and inventory.",
    isActive: true,
  },
  {
    slug: "skubana",
    name: "Extensiv Order Manager (Formerly Skubana)",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/1b6d33a6-e312-4ce9-80f1-2b93403c3784_tile_skubana.png",
    description: "Sync Extensiv Order Manager (Formerly Skubana) Orders, Products, Inventory, and Locations via Zimi.",
    documentation: "Extensiv Order Manager (formerly Skubana) finance connector. Supports Orders, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "skuvault",
    name: "SkuVault",
    logoUrl: "https://assets.lightspeedhq.com/img/2016/06/16fea4e5-standard-square-primary-1000-1.png",
    description: "Sync Orders, Inventory, Products, Fulfillments, and Locations via Handled.",
    documentation: "SkuVault ecommerce connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "slack",
    name: "Slack",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/slack_logo.png",
    description: "Send messages, create channels, and manage notifications in your Slack workspace through automated workflows",
    documentation: "Slack communication connector. Supports sending messages, managing channels, and workflow notifications.",
    isActive: true,
  },
  {
    slug: "sms",
    name: "SMS",
    logoUrl: "https://cdn-icons-png.flaticon.com/512/733/733533.png",
    description: "Send messages, and manage notifications on SMS through automated workflows",
    documentation: "SMS communication connector. Supports sending messages and managing notifications.",
    isActive: true,
  },
  {
    slug: "snowflake",
    name: "Snowflake",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ea8a85f0-071e-4c0f-800f-ea60a755fce4_tile_snowflake.png",
    description: "Sync Snowflake Orders, Products, Shipping Requests, Fulfillments, Inventory, Arrivals, Receipts, Purchase Orders, Transfer Orders, and Locations via Zimi.",
    documentation: "Snowflake finance connector. Supports Orders, Products, Shipping Requests, Fulfillments, Inventory, Arrivals, Receipts, Purchase Orders, Transfer Orders, and Locations.",
    isActive: true,
  },
  {
    slug: "som",
    name: "Salesforce Order Management",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/244b7990-3b78-4d36-b64d-e45b9116a67a_tile_salesforce.png",
    description: "Salesforce Order Management connector",
    documentation: "Salesforce Order Management ecommerce connector.",
    isActive: true,
  },
  {
    slug: "sos_inventory",
    name: "SOS Inventory",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ae46440e-da60-460a-95af-a90c21e1e045_tile_sos_inventory.png",
    description: "SOS Inventory connector",
    documentation: "SOS Inventory finance connector.",
    isActive: true,
  },
  {
    slug: "sps_ftp",
    name: "SPS FTP",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4644b513-e80a-48d7-aa23-b885f3f3ff37_tile_sps-ftp.png",
    description: "SPS FTP connector",
    documentation: "SPS FTP ecommerce connector.",
    isActive: true,
  },
  {
    slug: "square",
    name: "Square",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/48a33b88-3c5f-49a6-8498-65e0fb3d3f5f_tile_square.png",
    description: "Sync Square Orders, Products, Inventory, and Locations via Zimi.",
    documentation: "Square ecommerce connector. Supports Orders, Products, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "squarespace",
    name: "SquareSpace",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/25d2da6e-6e12-427a-8986-c9073f8f0f6f_tile_squarespace.png",
    description: "Sync SquareSpace orders, fulfillments, products and inventory via Zimi.",
    documentation: "SquareSpace ecommerce connector. Supports orders, fulfillments, products, and inventory.",
    isActive: true,
  },
  {
    slug: "stitchfix_edi",
    name: "StitchFix EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/6f3c0ba4-2998-408a-9067-8c3d12915040_tile_stitchfix_edi.png",
    description: "Sync StitchFix EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "StitchFix EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "target_edi",
    name: "Target EDI sales channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/b186b277-6533-420f-82b4-cc1ecbe9781d_tile_pipe17.png",
    description: "Sync Target EDI Orders, Fulfillments, and Inventory via Zimi.",
    documentation: "Target EDI ecommerce connector. Supports Orders, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "temu",
    name: "TEMU",
    logoUrl: "https://merchant.withzimi.com/zimi_logos/Iso_2.png",
    description: "Manage your TEMU orders, fulfillments, products and inventory via Zimi.",
    documentation: "TEMU ecommerce connector. Supports orders, fulfillments, products, and inventory.",
    isActive: true,
  },
  {
    slug: "thg",
    name: "The Hut Group",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/a2ca8693-dfd1-4fad-97e3-fe62cdafb5f3_tile_thg.png",
    description: "Sync Orders, Inventory, Fulfillments, and Locations via Zimi.",
    documentation: "The Hut Group ecommerce connector. Supports Orders, Inventory, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "tiktok",
    name: "Tiktok",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ded70a5f-52cf-4d46-b986-2de43133b416_tile_tiktok.png",
    description: "Manage your Tiktok orders, fulfillments, products and inventory via Zimi.",
    documentation: "TikTok Shop ecommerce connector. Supports Orders, Fulfillments, Products, and Inventory.",
    isActive: true,
  },
  {
    slug: "unis",
    name: "UNIS 3PL",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/15258473-3c48-4390-8539-cb377c7664b2_tile_unis.png",
    description: "UNIS 3PL connector",
    documentation: "UNIS 3PL logistics connector.",
    isActive: true,
  },
  {
    slug: "upscapital",
    name: "UPS Capital",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/d4307db2-93fc-4ca4-a60b-40af862e2b91_tile_upscapital.png",
    description: "Easily connect UPS Capital to Fulfillment.",
    documentation: "UPS Capital ecommerce connector.",
    isActive: true,
  },
  {
    slug: "ups_edi",
    name: "UPS EDI fulfillment channel",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7da03bc6-7a48-4379-822b-b12c4b0d9020_tile_pipe17.png",
    description: "Sync Orderful EDI Shipping requests, Fulfillments, and Inventory via Zimi.",
    documentation: "UPS EDI logistics connector. Supports Shipping Requests, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "veeqo",
    name: "Veeqo",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4c17dce9-e614-41b1-8855-02291f374a3f_tile_veeqo.png",
    description: "Sync Veeqo Orders, Products, Shipping Requests, Fulfillments, Inventory, and Locations via Zimi.",
    documentation: "Veeqo logistics connector. Supports Orders, Products, Shipping Requests, Fulfillments, Inventory, and Locations.",
    isActive: true,
  },
  {
    slug: "vend",
    name: "Vend",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/3963a6ab-2cbf-45ee-9310-982428c21f60_tile_vend.png",
    description: "Sync Vend Orders, Products, Inventory, Arrivals, Receipts, and Locations via Zimi.",
    documentation: "Vend ecommerce connector. Supports Orders, Products, Inventory, Arrivals, Receipts, and Locations.",
    isActive: true,
  },
  {
    slug: "veracore",
    name: "VeraCore",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/e5b2aea7-f28c-407a-80be-9eb32c84c79a_tile_veracore.png",
    description: "Sync with Zimi",
    documentation: "VeraCore logistics connector.",
    isActive: true,
  },
  {
    slug: "vtex",
    name: "VTEX",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/4405bcac-fe8a-4107-8ac3-124889a04b79_tile_vtex.png",
    description: "Easily connect VTEX to ERPs and Fulfillment, with rich Order and Inventory Management capabilities.",
    documentation: "VTEX ecommerce connector. Supports Order and Inventory Management.",
    isActive: true,
  },
  {
    slug: "walmart",
    name: "Walmart Marketplace",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/7c7425db-9b01-439f-9de4-aebf2109da5f_tile_walmart_marketplace.png",
    description: "Sync Walmart Orders, Inventory, and Fulfillments via Zimi.",
    documentation: "Walmart Marketplace ecommerce connector. Supports Orders, Inventory, and Fulfillments.",
    isActive: true,
  },
  {
    slug: "ware2go",
    name: "Ware2Go",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/dc3b11ed-8cae-4e9b-9a9f-1268bef342fe_tile_ware2go.png",
    description: "Sync Ware2Go Products, Inventory, Fulfillments, Shipping Requests, Arrivals, and Receipts via Zimi.",
    documentation: "Ware2Go logistics connector. Supports Products, Inventory, Fulfillments, Shipping Requests, Arrivals, and Receipts.",
    isActive: true,
  },
  {
    slug: "wayfair",
    name: "Wayfair",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/3693c90d-654a-4672-97f5-76ebb10f7cb4_tile_wayfair.png",
    description: "Sync Wayfair Orders, Products, Shipping Requests, Inventory, and Fulfillments via Zimi.",
    documentation: "Wayfair ecommerce connector. Supports Orders, Products, Shipping Requests, Inventory, and Fulfillments.",
    isActive: true,
  },
  {
    slug: "whatsapp",
    name: "Whatsapp",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/WhatsApp_icon.png",
    description: "Send messages, and manage notifications on Whatsapp through automated workflows",
    documentation: "WhatsApp communication connector. Supports sending messages and managing notifications.",
    isActive: true,
  },
  {
    slug: "whiplash",
    name: "Whiplash",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/ade41b12-acb2-4b69-b53d-82d649d36771_tile_whiplash.png",
    description: "Whiplash connector",
    documentation: "Whiplash logistics connector.",
    isActive: true,
  },
  {
    slug: "wix",
    name: "WiX",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/25432156-f1dc-4a2b-aedd-3e97510936bd_tile_wix.png",
    description: "Sync Wix Orders, Products, Fulfillments, and Inventory via Zimi.",
    documentation: "WiX ecommerce connector. Supports Orders, Products, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "woocommerce",
    name: "Woocommerce",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/woocommerce-logo.png",
    description: "Sync Orders, Inventory, Products, Fulfillments, and Locations via Zimi.",
    documentation: "WooCommerce ecommerce connector. Supports Orders, Inventory, Products, Fulfillments, and Locations.",
    isActive: true,
  },
  {
    slug: "xcart",
    name: "XCart",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/3555f145-2008-4a39-a2e6-d4018ca26e60_tile_xcart.png",
    description: "Sync XCart Orders, Products, Fulfillments, and Inventory via Zimi.",
    documentation: "XCart ecommerce connector. Supports Orders, Products, Fulfillments, and Inventory.",
    isActive: true,
  },
  {
    slug: "xero",
    name: "Xero",
    logoUrl: "https://zimi-landing-page.s3.us-east-2.amazonaws.com/8ff7ccba-d55b-42f0-9dd4-577fd8f558e3_tile_xero.png",
    description: "Sync Xero Orders, Products, Inventory, and Locations via Zimi.",
    documentation: "Xero finance connector. Supports Orders, Products, Inventory, and Locations.",
    isActive: true,
  },
];

async function main() {
  console.log(`Seeding ${mockServices.length} MockService records...`);

  for (const service of mockServices) {
    await prisma.mockService.upsert({
      where: { slug: service.slug },
      update: service,
      create: service,
    });
  }

  console.log(`Done. Seeded ${mockServices.length} mock services.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });